# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
jobs:
  include:
    - language: python
      python: 3.7
      script:
        - python mergesort.py

notifications:
  email:
    - karthikerathore@gmail.com
